### ISSUE TITLE
Forms

### ISSUE THREAD

**Issue by oganm** [notengrafik/fdf2xfdf#2]
In the readme you stated form data is already supported by various tools but I can't seem to be able to find any. Could you direct me towards one?

**Comment by th-we** [comment]
A quick search for "parse fdf form" gives me:

* https://www.adobe.com/devnet/acrobat/fdftoolkit.html
* https://www.php.net/manual/en/ref.fdf.php
* https://github.com/trockenasche/fdf2csv
* https://www.codeproject.com/Articles/8038/A-PDF-Forms-Parser
* https://www.codeproject.com/Tips/469385/FDF-NET-Parser

The format used for forms is also so much simpler than for annotations that it's quite easy to parse.
