### ISSUE TITLE
GroupNesting tag

### ISSUE THREAD

**Issue by sweco-sekrsv** [notengrafik/fdf2xfdf#3]
I'm having trouble adding a new type of extraction:

`/GroupNesting [(Skjutgrind 4m) /QBCWXVXWTOGGCBKV /DUGAXFCOVGOSUWTS]`

Can you help me adding it? I cant seem to understand how to iterate the values in the array.
I tried adding this:
```
  /GroupNesting {
    (GroupNesting) mark writeStartTag
	{} forall
    (GroupNesting) writeEndTag
    pop
  } bind
```

But it does not work.

**Comment by th-we** [comment]
What is `/GroupNesting`? It's not part of FDF or PDF.  What generates FDF with this content?

**Comment by sweco-sekrsv** [comment]
It's Bluebeam:) I'm attaching a sample fdf.
If I also can get the Groupnesting exported to xfdf I can parse that further. My plan is not to go back to fdf so for my case it does not matter if it's part of FDF or PDF.
[test.zip](https://github.com/notengrafik/fdf2xfdf/files/3862817/test.zip)

**Comment by th-we** [comment]
Can't you just export in a format that is more accessible, like [CSV or or XML](https://support.bluebeam.com/online-help/forms-help-2017/Content/Topics/Data.htm)?

**Comment by sweco-sekrsv** [comment]
I don't have Blubeam myself so I can't say if they provide other options for exporting.  Using your solution I get everything out that I need exept the GroupNesting part.

**Comment by th-we** [comment]
If you can't get hold of the people the data came from and if it's really important to you I could offer to implement this as paid work.

**Comment by sweco-sekrsv** [comment]
Thank you! I will consider it. You can close the issue
